easy_admin:
    site_name: 'SouthWestFrancePools'
    design:
        menu:
            - { entity: 'User', icon: 'users' }
            - { entity: 'Showcase', icon: 'file-image-o' }
            - { entity: 'Contact', icon: 'envelope-o' }