homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

about:
    path:     /about
    defaults: { _controller: AppBundle:Default:about }

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Default:contact }